name: Build code, run unit tests, and perform SAST, SCA, DAST security scans

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and run unit tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest flask-testing
      - name: Run unit tests
        run: pytest
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sca_scan:
    runs-on: ubuntu-latest
    needs: build_and_test
    name: Run SCA scan on the source code
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  dast_scan:
    runs-on: ubuntu-latest
    needs: sca_scan
    name: Run DAST scan on the web application
    steps:
      - uses: actions/checkout@v3
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://testphp.vulnweb.com/index.php'  # Replace with your deployed application URL
          docker_name: 'owasp/zap2docker-stable'
          cmd_options: '-a -m 5'
